name: manual_with_inputs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        type: string
        default: 'Your name here'
      age:
        description: 'Your age'
        type: number
        required: true
      gender:
        description: 'Your gender'
        type: choice
        options:
          - Male
          - Female
        required: true
      married:
        description: 'Are you married ?'
        type: boolean
        required: true
jobs:
  echo_inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo name
        run: echo 'your name' ${{inputs.name}}
      - name: Echo age
        run: echo 'your age' ${{inputs.age}}
      - name: Echo gender
        run: echo 'your gender' ${{inputs.gender}}
      - name: Ech married
        run: echo 'are you married' ${{inputs.married}}
