name: schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'
jobs:
  get_current_time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Current time
        run: echo 'Current time:'${{env.NOW}}
