name: Step Output
on:
 push:
   branches: [test_build_angular]
jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
   - name: Set output
     id: set_output
     shell: bash
     run: |
      echo "name=Edgar" >> $GITHUB_OUTPUT
      echo "age=20" >> $GITHUB_OUTPUT
   - name: Set output 2
     id: set_output_2
     shell: bash
     run: echo "salary=5000" >> $GITHUB_OUTPUT
   - name: Access output
     shell: bash
     run: |
      echo "Name is: "${{steps.set_output.outputs.name}}
      echo "Age is: "${{steps.set_output.outputs.age}}
      echo "Salary is: "${{steps.set_output2.outputs.salary}}
    
